version: "3.8"

services:
  paymybuddy-db:
    image: mysql:8
    container_name: paymybuddy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_paymybuddy
      MYSQL_USER: paymybuddy
      MYSQL_PASSWORD: paymybuddy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  paymybuddy-backend:
    image: paymybuddy-backend
    container_name: paymybuddy-backend
    restart: always
    depends_on:
      - paymybuddy-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
      SPRING_DATASOURCE_USERNAME: paymybuddy
      SPRING_DATASOURCE_PASSWORD: paymybuddy
    ports:
      - "8080:8080"

volumes:
  db_data:

